const creatorsData = [
  {
    id: 1,
    name: "Мария Левченко",
    email: "maria@example.com",
    bio: "Профессиональный художник-акварелист с 10-летним опытом. Провожу мастер-классы по живописи для всех уровней подготовки.",
    rating: 4.8,
    joined: "2020-03-15",
    stats: {
      masterClasses: 12,
      products: 8,
    },
    isVerified: true,
  },
  {
    id: 2,
    name: "Иван Козлов",
    email: "ivan@example.com",
    bio: "Мастер по дереву, создаю уникальные игрушки и предметы интерьера. Учу работать с деревом с нуля.",
    rating: 4.6,
    joined: "2021-08-22",
    stats: {
      masterClasses: 8,
      products: 15,
    },
    isVerified: false,
  },
  {
    id: 3,
    name: "Артём Артюшевский",
    email: "anna@example.com",
    bio: "Цифровой художник и иллюстратор. Специализируюсь на создании иллюстраций в Procreate.",
    rating: 4.9,
    joined: "2019-05-10",
    stats: {
      masterClasses: 6,
      products: 5,
    },
    isVerified: true,
  },
  {
    id: 4,
    name: "Ольга Смирнова",
    email: "olga@example.com",
    bio: "Мастер керамики и гончарного дела. Учу создавать посуду и декор из глины.",
    rating: 4.7,
    joined: "2020-11-30",
    stats: {
      masterClasses: 7,
      products: 12,
    },
    isVerified: true,
  },
  {
    id: 5,
    name: "Алексей Морозов",
    email: "alexey@example.com",
    bio: "Художник масляной живописи. Преподаю классические техники и современные подходы.",
    rating: 4.5,
    joined: "2021-04-18",
    stats: {
      masterClasses: 9,
      products: 3,
    },
    isVerified: false,
  },
  {
    id: 6,
    name: "Екатерина Сидорова",
    email: "ekaterina@example.com",
    bio: "Дизайнер ювелирных украшений из полимерной глины и эпоксидной смолы.",
    rating: 4.8,
    joined: "2022-01-10",
    stats: {
      masterClasses: 5,
      products: 20,
    },
    isVerified: true,
  },
  {
    id: 7,
    name: "Дмитрий Волков",
    email: "dmitry@example.com",
    bio: "Каллиграф и леттерер. Преподаю искусство красивого письма и современную каллиграфию.",
    rating: 4.7,
    joined: "2019-09-05",
    stats: {
      masterClasses: 4,
      products: 8,
    },
    isVerified: false,
  },
  {
    id: 8,
    name: "Татьяна Новикова",
    email: "tatiana@example.com",
    bio: "Мастер по вязанию и созданию текстильных изделий. Учу вязать спицами и крючком.",
    rating: 4.6,
    joined: "2020-07-20",
    stats: {
      masterClasses: 10,
      products: 18,
    },
    isVerified: true,
  },
  {
    id: 9,
    name: "Сергей Петров",
    email: "sergey@example.com",
    bio: "Фотограф и ретушер. Преподаю основы фотографии и обработки в Lightroom и Photoshop.",
    rating: 4.4,
    joined: "2021-02-14",
    stats: {
      masterClasses: 3,
      products: 6,
    },
    isVerified: false,
  },
  {
    id: 10,
    name: "Наталья Ковалёва",
    email: "natalya@example.com",
    bio: "Мастер по созданию ароматических свечей и косметики ручной работы.",
    rating: 4.9,
    joined: "2022-03-01",
    stats: {
      masterClasses: 7,
      products: 25,
    },
    isVerified: true,
  },
  {
    id: 11,
    name: "Павел Григорьев",
    email: "pavel@example.com",
    bio: "Скетчер и иллюстратор. Специализируюсь на быстрых зарисовках алкогольными маркерами.",
    rating: 4.5,
    joined: "2020-10-12",
    stats: {
      masterClasses: 5,
      products: 9,
    },
    isVerified: false,
  },
  {
    id: 12,
    name: "Юлия Захарова",
    email: "yulia@example.com",
    bio: "Флорист и дизайнер цветочных композиций. Учу искусству составления букетов.",
    rating: 4.8,
    joined: "2021-05-25",
    stats: {
      masterClasses: 6,
      products: 14,
    },
    isVerified: true,
  },
  {
    id: 13,
    name: "Андрей Белов",
    email: "andrey@example.com",
    bio: "Гончарный мастер с 15-летним стажем. Преподаю работу на гончарном круге.",
    rating: 4.9,
    joined: "2018-12-03",
    stats: {
      masterClasses: 11,
      products: 7,
    },
    isVerified: true,
  },
  {
    id: 14,
    name: "Ирина Фёдорова",
    email: "irina@example.com",
    bio: "Мастер по созданию натурального мыла и косметики ручной работы.",
    rating: 4.7,
    joined: "2021-09-17",
    stats: {
      masterClasses: 4,
      products: 22,
    },
    isVerified: false,
  },
  {
    id: 15,
    name: "Михаил Соколов",
    email: "mikhail@example.com",
    bio: "Музыкант и преподаватель игры на укулеле. Учу с нуля до уверенного владения инструментом.",
    rating: 4.4,
    joined: "2022-06-08",
    stats: {
      masterClasses: 3,
      products: 2,
    },
    isVerified: false,
  },
];

export default creatorsData;
