const popularClasses = [
  {
    id: 1,
    title: "Акварельный пейзаж",
    author: "Мария Левченко",
    rating: 4.8,
    image: null,
    category: "Живопись",
    description: "Научитесь создавать атмосферные пейзажи акварелью",
    tags: ["акварель", "пейзаж", "для начинающих"],
    views: 100,
  },
  {
    id: 2,
    title: "Деревянная игрушка своими руками",
    author: "Иван Козлов",
    rating: 4.6,
    image: null,
    category: "Столярное дело",
    description: "Создание деревянных игрушек с нуля",
    tags: ["дерево", "игрушки", "handmade"],
    views: 100,
  },
  {
    id: 3,
    title: "Цифровая иллюстрация в Procreate",
    author: "Анна Грин",
    rating: 4.9,
    image: null,
    category: "Цифровое искусство",
    description: "Профессиональная иллюстрация на iPad",
    tags: ["procreate", "digital art", "иллюстрация"],
    views: 1000,
  },
  {
    id: 4,
    title: "Керамика для начинающих",
    author: "Ольга Смирнова",
    rating: 4.7,
    image: null,
    category: "Керамика",
    description: "Основы работы с глиной и гончарным кругом",
    tags: ["керамика", "глина", "гончарное дело"],
    views: 100,
  },
  {
    id: 5,
    title: "Базовый курс по вязанию",
    author: "Татьяна Новикова",
    rating: 4.5,
    image: null,
    category: "Вязание",
    description: "Вязание спицами и крючком для новичков",
    tags: ["вязание", "спицы", "крючок"],
    views: 100,
  },
  {
    id: 6,
    title: "Современная каллиграфия",
    author: "Дмитрий Волков",
    rating: 4.8,
    image: null,
    category: "Каллиграфия",
    description: "Искусство красивого письма",
    tags: ["каллиграфия", "леттеринг", "шрифты"],
    views: 1000,
  },
  {
    id: 7,
    title: "Фотография на смартфон",
    author: "Сергей Петров",
    rating: 4.4,
    image: null,
    category: "Фотография",
    description: "Профессиональные снимки на телефон",
    tags: ["фотография", "смартфон", "обработка"],
    views: 1300,
  },
  {
    id: 8,
    title: "Создание украшений из полимерной глины",
    author: "Екатерина Сидорова",
    rating: 4.9,
    image: null,
    category: "Бижутерия",
    description: "Авторские украшения своими руками",
    tags: ["полимерная глина", "украшения", "handmade"],
    views: 1030,
  },
  {
    id: 9,
    title: "Основы масляной живописи",
    author: "Алексей Морозов",
    rating: 4.7,
    image: null,
    category: "Живопись",
    description: "Классическая техника масляной живописи",
    tags: ["масло", "живопись", "классика"],
    views: 10,
  },
  {
    id: 10,
    title: "Создание свечей ручной работы",
    author: "Наталья Ковалева",
    rating: 4.6,
    image: null,
    category: "Декоративно-прикладное искусство",
    description: "Ароматические и декоративные свечи",
    tags: ["свечи", "ароматерапия", "декор"],
    views: 120,
  },
  {
    id: 11,
    title: "Флористика для начинающих",
    author: "Юлия Захарова",
    rating: 4.8,
    image: null,
    category: "Флористика",
    description: "Искусство составления букетов",
    tags: ["флористика", "цветы", "букеты"],
    views: 1110,
  },
  {
    id: 12,
    title: "Скетчинг маркерами",
    author: "Павел Григорьев",
    rating: 4.5,
    image: null,
    category: "Рисование",
    description: "Быстрые зарисовки алкогольными маркерами",
    tags: ["скетчинг", "маркеры", "скетчбук"],
    views: 100,
  },
  {
    id: 13,
    title: "Изготовление мыла ручной работы",
    author: "Ирина Федорова",
    rating: 4.7,
    image: null,
    category: "Косметика",
    description: "Натуральное мыло своими руками",
    tags: ["мыло", "натуральное", "косметика"],
    views: 100,
  },
  {
    id: 14,
    title: "Курс по макетированию в Figma",
    author: "Артем Васильев",
    rating: 4.9,
    image: null,
    category: "Дизайн",
    description: "Создание интерфейсов и прототипов",
    tags: ["figma", "ui/ux", "дизайн"],
    views: 100,
  },
  {
    id: 15,
    title: "Лепка из холодного фарфора",
    author: "Светлана Орлова",
    rating: 4.6,
    image: null,
    category: "Лепка",
    description: "Цветы и фигурки из холодного фарфора",
    tags: ["фарфор", "лепка", "цветы"],
    views: 100,
  },
  {
    id: 16,
    title: "Основы игры на укулеле",
    author: "Михаил Соколов",
    rating: 4.4,
    image: null,
    category: "Музыка",
    description: "Быстрый старт в игре на укулеле",
    tags: ["укулеле", "музыка", "инструменты"],
    views: 100,
  },
  {
    id: 17,
    title: "Декупаж для начинающих",
    author: "Оксана Михайлова",
    rating: 4.5,
    image: null,
    category: "Декорирование",
    description: "Техника декорирования предметов",
    tags: ["декупаж", "декор", "салфеточная техника"],
    views: 100,
  },
  {
    id: 18,
    title: "Создание интерьерных картин",
    author: "Виктор Павлов",
    rating: 4.8,
    image: null,
    category: "Интерьер",
    description: "Абстрактные картины для дома",
    tags: ["интерьер", "абстракция", "декор"],
    views: 100,
  },
  {
    id: 19,
    title: "Курс по работе с эпоксидной смолой",
    author: "Елена Никитина",
    rating: 4.7,
    image: null,
    category: "Рукоделие",
    description: "Создание изделий из эпоксидной смолы",
    tags: ["эпоксидка", "смола", "ювелирка"],
    views: 100,
  },
  {
    id: 20,
    title: "Основы гончарного мастерства",
    author: "Андрей Белов",
    rating: 4.9,
    image: null,
    category: "Керамика",
    description: "Классическая работа на гончарном круге",
    tags: ["гончарка", "керамика", "посуда"],
    views: 100,
  },
  {
    id: 21,
    title: "Создание мозаики",
    author: "Марина Семенова",
    rating: 4.6,
    image: null,
    category: "Декоративно-прикладное искусство",
    description: "Мозаичные панно и украшения",
    tags: ["мозаика", "декор", "панно"],
    views: 100,
  },
  {
    id: 22,
    title: "Курс по пастельной живописи",
    author: "Денис Кириллов",
    rating: 4.7,
    image: null,
    category: "Рисование",
    description: "Нежная живопись сухой пастелью",
    tags: ["пастель", "живопись", "портрет"],
    views: 100,
  },
  {
    id: 23,
    title: "Изготовление украшений из кожи",
    author: "Алина Яковлева",
    rating: 4.8,
    image: null,
    category: "Бижутерия",
    description: "Кожаные браслеты, серьги и колье",
    tags: ["кожа", "украшения", "handmade"],
    views: 100,
  },
  {
    id: 24,
    title: "Основы анимации в After Effects",
    author: "Роман Фролов",
    rating: 4.9,
    image: null,
    category: "Анимация",
    description: "Создание motion-графики",
    tags: ["after effects", "анимация", "motion"],
    views: 100,
  },
  {
    id: 25,
    title: "Курс по шаромутию",
    author: "Лариса Дмитриева",
    rating: 4.5,
    image: null,
    category: "Рукоделие",
    description: "Войлочные игрушки и украшения",
    tags: ["шаромутие", "войлок", "игрушки"],
    views: 100,
  },
];

export default popularClasses;
